ConfigureErrors:
  mongo (1.14.0):
  - |-
    could not invoke 'mongo' python check constructor. New constructor API returned:
    Traceback (most recent call last):
      File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/mongo/mongo.py", line 93, in __init__
        raise ConfigurationError("Missing 'server' in mongo config")
    datadog_checks.base.errors.ConfigurationError: Missing 'server' in mongo config
    Deprecated constructor API returned:
    __init__() got an unexpected keyword argument 'agentConfig'
Py3Warnings: {}